title: Art by Alice
author: Alice Ballouz
email: a
description: >-
  In her practice, Alice Ballouz has explored her love of colours and shapes in different materials and mediums. 
  Self-taught, Alice began painting as a means of dealing with the COVID-19 Pandemic Lockdown.
  Alice has experimented with abstract shapes using the paint pouring technique

social:
  instagram: art_alices
  github: sarbal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
